# Mongo-Sync Configurations

local:
  db: 'local_db_name'
  host:
    url: '127.0.0.1'
    port: 27017
  access:
    username: 'local_mongo_user'
    password: 'local_mongo_pass'

remote:
  db: 'remote_db_name'
  host:
    url: 'some.remoteurl.com'
    port: 27017
  access:
    username: 'remote_mongo_user'
    password: 'remote_mongo_pass'

# For now :local only accepts DB name and port
# Assumes DB is at localhost:port

# All of the parameters above are required,
# without them, the script will fail
